version: '3'
services:
  go:
    build: .
    command: "${DGT_CMD:-}"
    depends_on:
      db:
        condition: service_healthy
    ports:
        - 8080:8080
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
  db:
    build: ./database
    environment:
      - MYSQL_DATABASE=dgt
      - MYSQL_ROOT_PASSWORD=passw0rd
      - character-set-server="utf8mb4"
      - collation-server="utf8mb4_unicode_ci"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
        - 3306:3306