version: '3'
services:
  go:
    build: .
    command: "${DGT_CMD:-}"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      db:
        condition: service_healthy
    ports:
        - 8080:8080
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-b:
    image: dgt-go:latest
    command: "scrap --persist --from 0000BBB --until 9999BZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-c:
    image: dgt-go:latest
    command: "scrap --persist --from 0000CBB --until 9999CZZ"
    depends_on:
      go:
        condition: service_started 
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-d:
    image: dgt-go:latest
    command: "scrap --persist --from 0000DBB --until 9999DZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-f:
    image: dgt-go:latest
    command: "scrap --persist --from 0000FBB --until 9999FZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-g:
    image: dgt-go:latest
    command: "scrap --persist --from 0000GBB --until 9999GZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-h:
    image: dgt-go:latest
    command: "scrap --persist --from 0000HBB --until 9999HZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-j:
    image: dgt-go:latest
    command: "scrap --persist --from 0000JBB --until 9999JZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-k:
    image: dgt-go:latest
    command: "scrap --persist --from 0000KBB --until 9999KZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-l:
    image: dgt-go:latest
    command: "scrap --persist --from 0000LBB --until 9999LZZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  go-m:
    image: dgt-go:latest
    command: "scrap --persist --from 0000MBB --until 9999MCZ"
    depends_on:
      go:
        condition: service_started
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - MYSQL_SERVER=db
      - MYSQL_ROOT_PASSWORD=passw0rd

  db:
    build: ./database
    environment:
      - MYSQL_DATABASE=dgt
      - MYSQL_ROOT_PASSWORD=passw0rd
      - character-set-server="utf8mb4"
      - collation-server="utf8mb4_unicode_ci"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppassw0rd" , "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
        - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M